[package]
name = "git-backup"
version = "0.1.0"
authors = ["James Wilson <james@jsdw.me>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
rayon = "1"
regex = "1.3.1"
reqwest = "0.9.20"
serde = "1"
serde_json = "1"
structopt = "0.3.1"